// 完整版菜单比较多，将 rank 抽离出来，在此方便维护

const home = 0, // 平台规定只有 home 路由的 rank 才能为 0 ，所以后端在返回 rank 的时候需要从非 0 开始
  dashboard = 1,
  storeGovernance = 2,
  goodsGovernance = 3,
  orderGovernance = 4,
  marketingGovernance = 5,
  fundGovernance = 6,
  procurementGovernance = 6.5,
  platformConfig = 7,
  memberCenter = 8,
  messageCenter = 9,
  contentCenter = 10,
  supportCenter = 11,
  merchantGrant = 12,
  chatai = 13,
  vueflow = 14,
  ganttastic = 15,
  components = 16,
  able = 17,
  table = 18,
  form = 19,
  list = 20,
  result = 21,
  error = 22,
  frame = 23,
  nested = 24,
  permission = 25,
  system = 26,
  monitor = 27,
  tabs = 28,
  about = 29,
  codemirror = 30,
  markdown = 31,
  editor = 32,
  flowchart = 33,
  formdesign = 34,
  board = 35,
  ppt = 36,
  mind = 37,
  guide = 38,
  menuoverflow = 39;

export {
  home,
  dashboard,
  storeGovernance,
  goodsGovernance,
  orderGovernance,
  marketingGovernance,
  fundGovernance,
  procurementGovernance,
  platformConfig,
  memberCenter,
  messageCenter,
  contentCenter,
  supportCenter,
  merchantGrant,
  chatai,
  vueflow,
  ganttastic,
  components,
  able,
  table,
  form,
  list,
  result,
  error,
  frame,
  nested,
  permission,
  system,
  monitor,
  tabs,
  about,
  codemirror,
  markdown,
  editor,
  flowchart,
  formdesign,
  board,
  ppt,
  mind,
  guide,
  menuoverflow
};
