CREATE TABLE IF NOT EXISTS `li_verification_record` (
    `id` varchar(64) NOT NULL COMMENT '主键ID',
    `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
    `update_time` datetime DEFAULT NULL COMMENT '更新时间',
    `delete_flag` tinyint(1) DEFAULT 0 COMMENT '删除标记',
    `order_sn` varchar(64) NOT NULL COMMENT '订单编号',
    `store_id` varchar(64) DEFAULT NULL COMMENT '店铺ID',
    `store_name` varchar(255) DEFAULT NULL COMMENT '店铺名称',
    `member_id` varchar(64) DEFAULT NULL COMMENT '会员ID',
    `member_name` varchar(255) DEFAULT NULL COMMENT '会员名称',
    `verification_code` varchar(64) NOT NULL COMMENT '核销码',
    `operator_id` varchar(64) DEFAULT NULL COMMENT '核销人ID',
    `operator_name` varchar(255) DEFAULT NULL COMMENT '核销人名称',
    `source_type` varchar(32) NOT NULL COMMENT '核销来源',
    `result_type` varchar(32) NOT NULL COMMENT '核销结果',
    `remark` varchar(255) DEFAULT NULL COMMENT '核销备注',
    `verify_time` datetime DEFAULT NULL COMMENT '核销时间',
    PRIMARY KEY (`id`),
    KEY `idx_verification_record_order_sn` (`order_sn`),
    KEY `idx_verification_record_store_id` (`store_id`),
    KEY `idx_verification_record_code` (`verification_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='核销记录';
